version: '2'
services:
  tomcat:
    image: "tomcat:8.5.15-jre8"
    ports:
      - "8080:8080"
      - "1099:1099"
      - "62911:62911"
    volumes:
      - tomcat-webapps:/usr/local/tomcat/webapps
      - tomcat-work:/usr/local/tomcat/work
      - ../data/tomcat-logs:/usr/local/tomcat/logs
      - ../containers/tomcat/settings.xml:/usr/local/tomcat/conf/settings.xml
      - ../containers/tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    environment:
      - HOST_IP=${HOST_IP}
    env_file:
      - ../env/tomcat.env
